name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rye
        uses: eifinger/setup-rye@v2

      - name: Install dependencies
        run: rye sync

      - name: Ruff check
        run: rye run ruff check src

      - name: Ruff format check
        run: rye run ruff format --check src

      - name: Mypy
        run: rye run mypy src

      - name: Test
        run: rye test
